language: node_js
node_js: 
  - "stable"
cache:
  - npm
before_script:
  - npm ci
script: 
  - npm run test
  - npm run deploy
  - now alias --token=$FK9wXzDMgwcdkILcFofjyOeS -V 2 jsdom-kpi-schedle-$TRAVIS_BRANCH